// <auto-generated />
using System;
using EncoreLedger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EncoreLedger.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("EncoreLedger.Models.Account", b =>
                {
                    b.Property<int>("IDAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .HasColumnType("TEXT");

                    b.HasKey("IDAccount");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("EncoreLedger.Models.BulkImport", b =>
                {
                    b.Property<int>("IDBulkImport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecordsFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecordsImported")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalRecords")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDBulkImport");

                    b.ToTable("BulkImport", (string)null);
                });

            modelBuilder.Entity("EncoreLedger.Models.Category", b =>
                {
                    b.Property<int>("IDCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("IDCategory");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("EncoreLedger.Models.Transaction", b =>
                {
                    b.Property<int>("IDTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("BulkImportID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEdited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsertType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("IDTransaction");

                    b.HasIndex("AccountID");

                    b.HasIndex("BulkImportID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("EncoreLedger.Models.Transaction", b =>
                {
                    b.HasOne("EncoreLedger.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EncoreLedger.Models.BulkImport", "BulkImport")
                        .WithMany("Transactions")
                        .HasForeignKey("BulkImportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EncoreLedger.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("BulkImport");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EncoreLedger.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EncoreLedger.Models.BulkImport", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EncoreLedger.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
